// app/estoque/page.tsx
'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, Archive, BadgeDollarSign, BarChart3, Boxes, ChevronLeft, ClipboardCheck, History, ListChecks, PackagePlus, Plus, Search, Store, Wallet, WandSparkles } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { purchaseSuggestion, stockLevel, stockValue } from '@/lib/stock';
import { SUPPLY_UNIT_LABELS } from '@/lib/stock-supply';

export default function StockPage() {
  const router = useRouter(); const products = useAppStore((state) => state.stockProducts); const movements = useAppStore((state) => state.stockMovements);
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'todos'|'baixo'|'zero'>('todos');
  const active=useMemo(()=>products.filter(p=>p.active),[products]); const low=active.filter(p=>stockLevel(p)!=='ok');
  const filtered=active.filter(p=>p.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))&&(filter==='todos'||stockLevel(p)===filter));
  const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  return <div className="flex flex-col gap-5 pb-28"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={()=>router.replace('/loja')} className="grid h-12 w-12 place-items-center rounded-full border border-zinc-800 bg-zinc-900 text-zinc-400"><ChevronLeft size={21}/></button><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-400">Controle físico</p><h1 className="font-heading text-2xl font-black text-zinc-100">Estoque</h1></div></div><button onClick={()=>router.push('/estoque/novo')} className="flex h-12 items-center gap-2 rounded-2xl bg-emerald-500 px-4 font-black text-zinc-950"><Plus size={18}/>Produto</button></header>
  <section className="grid grid-cols-2 gap-3"><Metric icon={Boxes} label="Produtos ativos" value={String(active.length)}/><Metric icon={AlertTriangle} label="Pedem atenção" value={String(low.length)} alert={low.length>0}/><Metric icon={Wallet} label="Valor estimado" value={money(stockValue(active))}/><Metric icon={History} label="Movimentações" value={String(movements.length)}/></section>
  <section className="grid grid-cols-4 gap-2"><Shortcut icon={ClipboardCheck} label="Contagem" color="text-sky-400" onClick={()=>router.push('/estoque/contagem')}/><Shortcut icon={ListChecks} label="Lista" color="text-amber-400" onClick={()=>router.push('/estoque/compras')}/><Shortcut icon={BarChart3} label="Relatórios" color="text-emerald-400" onClick={()=>router.push('/estoque/relatorios')}/><Shortcut icon={Archive} label="Arquivados" color="text-zinc-400" onClick={()=>router.push('/estoque/arquivados')}/><Shortcut icon={Store} label="Fornecedores" color="text-orange-400" onClick={()=>router.push('/estoque/fornecedores')}/><Shortcut icon={BadgeDollarSign} label="Preços" color="text-lime-400" onClick={()=>router.push('/estoque/precos')}/><Shortcut icon={WandSparkles} label="Catálogo" color="text-violet-400" onClick={()=>router.push('/estoque/catalogo')}/></section>
  {low.length>0&&<button onClick={()=>router.push('/estoque/compras')} className="rounded-[24px] border border-amber-500/25 bg-amber-500/[.06] p-4 text-left"><p className="text-xs font-black text-amber-400">Lista de compra sugerida</p><p className="mt-1 text-[11px] text-zinc-400">{low.map(p=>`${p.name}: ${purchaseSuggestion(p).toLocaleString('pt-BR')} ${SUPPLY_UNIT_LABELS[p.unit]}`).join(' • ')}</p></button>}
  <div className="relative"><Search size={19} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto" className="h-14 w-full rounded-2xl border border-zinc-800 bg-zinc-900/50 pl-12 pr-4 text-zinc-100 outline-none focus:border-emerald-500"/></div>
  <div className="grid grid-cols-3 gap-2">{(['todos','baixo','zero'] as const).map(key=><button key={key} onClick={()=>setFilter(key)} className={`h-11 rounded-xl border text-xs font-bold ${filter===key?'border-emerald-500/40 bg-emerald-500/10 text-emerald-400':'border-zinc-800 bg-zinc-900 text-zinc-500'}`}>{key==='todos'?'Todos':key==='baixo'?'Baixo':'Zerado'}</button>)}</div>
  <section className="space-y-3">{filtered.map(product=>{const level=stockLevel(product);return <article key={product.id} onClick={()=>router.push(`/estoque/detalhes?id=${product.id}`)} className="cursor-pointer rounded-[24px] border border-zinc-800 bg-zinc-900/50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-heading font-black text-zinc-100">{product.name}</p><p className="mt-1 text-xs text-zinc-500">{product.category||'Sem categoria'}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${level==='ok'?'bg-emerald-500/10 text-emerald-400':'bg-amber-500/10 text-amber-400'}`}>{level==='ok'?'Em dia':level==='zero'?'Zerado':'Baixo'}</span></div><div className="mt-4 flex items-end justify-between border-t border-zinc-800/70 pt-3"><div><p className="font-heading text-2xl font-black text-zinc-100">{product.current_quantity.toLocaleString('pt-BR')}</p><p className="text-[10px] text-zinc-500">{SUPPLY_UNIT_LABELS[product.unit]} · mínimo {product.minimum_quantity.toLocaleString('pt-BR')}</p></div><button onClick={(event)=>{event.stopPropagation();router.push(`/estoque/movimentar?id=${product.id}`)}} className="flex h-10 items-center gap-2 rounded-xl bg-emerald-500 px-3 text-xs font-black text-zinc-950"><ClipboardCheck size={15}/>Movimentar</button></div></article>})}{!filtered.length&&<div className="rounded-[28px] border border-dashed border-zinc-800 py-14 text-center"><PackagePlus size={34} className="mx-auto text-zinc-700"/><p className="mt-3 text-sm font-bold text-zinc-400">Nenhum produto encontrado</p></div>}</section></div>;
}
function Metric({icon:Icon,label,value,alert}:{icon:typeof Boxes;label:string;value:string;alert?:boolean}){return <div className={`min-w-0 rounded-[22px] border p-4 ${alert?'border-amber-500/25 bg-amber-500/[.05]':'border-zinc-800 bg-zinc-900/45'}`}><Icon size={16} className={alert?'text-amber-400':'text-emerald-400'}/><p className="mt-3 truncate font-heading text-xl font-black text-zinc-100">{value}</p><p className="mt-1 text-[10px] font-bold text-zinc-600">{label}</p></div>}
function Shortcut({icon:Icon,label,color,onClick}:{icon:typeof Boxes;label:string;color:string;onClick:()=>void}){return <button onClick={onClick} className="min-w-0 rounded-2xl border border-zinc-800 bg-zinc-900/55 p-3 text-left"><Icon size={17} className={color}/><p className="mt-2 truncate text-[9px] font-black text-zinc-300">{label}</p></button>}
