'use client';
import { useEffect,useMemo,useState } from 'react';import { Check,Download,Save,ShoppingCart,WifiOff } from 'lucide-react';import { toast } from 'sonner';
import type { StockSupply,StockSupplyItem } from '@/types';import { formatBRLCents,moneyToNumber,numberToBRLInput } from '@/lib/money-input';import { downloadShoppingListPdf } from '@/lib/shopping-list-pdf';import { formatStockQuantity } from '@/lib/stock-quantity';
type Draft={checked:Record<string,boolean>;prices:Record<string,string>};const storageKey=(id:string)=>`dfl-shopping-session:${id}`;
export function ShoppingSession({supply,onFinish,busy}:{supply:StockSupply;onFinish:(items:StockSupplyItem[])=>Promise<void>;busy:boolean}){
 const initial=():Draft=>{try{return JSON.parse(localStorage.getItem(storageKey(supply.id))||'null')||{checked:{},prices:Object.fromEntries(supply.items.map(i=>[i.id,numberToBRLInput(i.purchase_unit_price??i.total_price)]))}}catch{return{checked:{},prices:{}}}};const [draft,setDraft]=useState<Draft>(initial);useEffect(()=>localStorage.setItem(storageKey(supply.id),JSON.stringify(draft)),[draft,supply.id]);const count=Object.values(draft.checked).filter(Boolean).length;
 const items=useMemo(()=>supply.items.map(item=>{const price=moneyToNumber(draft.prices[item.id]||''),purchaseQty=item.purchase_quantity??1;return{...item,purchase_unit_price:price||undefined,total_price:price?Number((price*purchaseQty).toFixed(2)):undefined,unit_price:price?Number((price/(item.conversion_quantity||1)).toFixed(4)):undefined}}),[draft.prices,supply.items]);const total=items.reduce((sum,i)=>sum+(i.total_price||0),0);
 const finish=async()=>{if(count!==items.length)return toast.error('Marque todos os itens antes de finalizar.');try{await onFinish(items);localStorage.removeItem(storageKey(supply.id))}catch{toast.error('Sem conexão. A compra continua salva neste aparelho.')}};
 return <section className="mt-5 rounded-[28px] border border-amber-500/25 bg-amber-500/[.04] p-4"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-500/10 text-amber-400"><ShoppingCart size={19}/></span><div className="flex-1"><h2 className="font-heading font-black text-zinc-100">Compra em andamento</h2><p className="mt-1 text-[10px] text-zinc-500">{count}/{items.length} itens · salvo automaticamente neste aparelho.</p></div><WifiOff size={15} className="text-zinc-600"/></div><div className="mt-4 space-y-2">{items.map(item=><article key={item.id} className={`rounded-2xl border p-3 ${draft.checked[item.id]?'border-emerald-500/30 bg-emerald-500/[.05]':'border-zinc-800 bg-zinc-950/50'}`}><button type="button" onClick={()=>setDraft(v=>({...v,checked:{...v.checked,[item.id]:!v.checked[item.id]}}))} className="flex w-full items-center gap-3 text-left"><span className={`grid h-9 w-9 place-items-center rounded-xl border ${draft.checked[item.id]?'border-emerald-500 bg-emerald-500 text-zinc-950':'border-zinc-700 text-zinc-600'}`}><Check size={16}/></span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-zinc-100">{item.name}</b><small className="text-zinc-500">{item.purchase_quantity&&item.presentation_label?`${item.purchase_quantity} × ${item.presentation_label}`:formatStockQuantity(item.quantity,item.unit)}</small></span></button><label className="mt-3 block text-[10px] font-bold text-zinc-500">Preço real por {item.presentation_label||item.purchase_unit||item.unit}<input inputMode="numeric" value={draft.prices[item.id]||'R$ 0,00'} onChange={e=>setDraft(v=>({...v,prices:{...v.prices,[item.id]:formatBRLCents(e.target.value)}}))} className="mt-1 h-11 w-full rounded-xl border border-zinc-800 bg-zinc-900 px-3 font-bold text-zinc-100 outline-none focus:border-amber-500"/></label></article>)}</div><div className="mt-4 flex justify-between rounded-2xl bg-zinc-950/60 p-3 text-xs"><span className="text-zinc-500">Total dos produtos</span><b className="text-emerald-400">{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>downloadShoppingListPdf({...supply,items,total_amount:total},draft.checked)} className="flex h-12 items-center justify-center gap-2 rounded-xl border border-zinc-700 text-xs font-black text-zinc-300"><Download size={16}/>Baixar PDF</button><button type="button" disabled={busy||count!==items.length} onClick={finish} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-emerald-500 text-xs font-black text-zinc-950 disabled:opacity-40"><Save size={16}/>Finalizar compra</button></div></section>
}
