// app/estoque/precos/page.tsx
'use client';
import { useMemo, useState } from 'react';
import { BadgeDollarSign, Search, Store, TrendingDown } from 'lucide-react';
import { PageHeader } from '@/components/layout/PageHeader';
import { useAppStore } from '@/store/useAppStore';
import { buildStockPriceInsights } from '@/lib/stock-pricing';
import { SUPPLY_UNIT_LABELS } from '@/lib/stock-supply';
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function PricesPage(){const products=useAppStore(s=>s.stockProducts);const supplies=useAppStore(s=>s.stockSupplies);const suppliers=useAppStore(s=>s.stockSuppliers);const [query,setQuery]=useState('');const insights=useMemo(()=>buildStockPriceInsights(products,supplies,suppliers),[products,suppliers,supplies]);const filtered=insights.filter(i=>i.product.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));return <div className="pb-28"><PageHeader title="Inteligência de preços" subtitle="Comparações por unidade real" to="/estoque"/><section className="mb-4 rounded-[26px] border border-emerald-500/20 bg-emerald-500/[.05] p-4"><div className="flex gap-3"><BadgeDollarSign className="text-emerald-400"/><div><p className="text-sm font-black text-zinc-100">{insights.length} produto{insights.length===1?'':'s'} com histórico</p><p className="mt-1 text-[10px] leading-relaxed text-zinc-500">A mediana reduz distorções de compras fora do padrão. A confiança cresce com a amostra.</p></div></div></section><div className="relative mb-4"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto" className="h-14 w-full rounded-2xl border border-zinc-800 bg-zinc-900 pl-12 pr-4 text-zinc-100 outline-none focus:border-emerald-500"/></div><div className="space-y-3">{filtered.map(i=><article key={i.product.id} className="rounded-[24px] border border-zinc-800 bg-zinc-900/50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-heading font-black text-zinc-100">{i.product.name}</p><p className="mt-1 text-[10px] text-zinc-600">{i.samples} compra{i.samples===1?'':'s'} · confiança {i.confidence}</p></div>{Boolean(i.savingPercent)&&<span className="flex items-center gap-1 rounded-full bg-emerald-500/10 px-2.5 py-1 text-[10px] font-black text-emerald-400"><TrendingDown size={12}/>{i.savingPercent!.toFixed(0)}%</span>}</div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Último" value={money(i.latest)}/><Metric label="Mediana" value={money(i.median)}/><Metric label="Menor" value={money(i.lowest)}/></div><p className="mt-3 flex items-center gap-2 border-t border-zinc-800/70 pt-3 text-[10px] text-zinc-500"><Store size={13} className="text-amber-400"/>Melhor histórico: <b className="text-zinc-300">{i.bestSupplier}</b> · por {SUPPLY_UNIT_LABELS[i.product.unit].toLocaleLowerCase('pt-BR')}</p></article>)}{!filtered.length&&<div className="rounded-[26px] border border-dashed border-zinc-800 py-14 text-center"><BadgeDollarSign className="mx-auto text-zinc-700"/><p className="mt-3 text-sm font-bold text-zinc-400">Ainda não há compras comparáveis</p><p className="mt-1 text-xs text-zinc-600">Os insights surgem com o histórico real.</p></div>}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl bg-zinc-950/60 p-2"><p className="text-[8px] font-bold uppercase text-zinc-600">{label}</p><p className="mt-1 truncate text-[11px] font-black text-zinc-200">{value}</p></div>}
