import type { Delivery } from '@/types';
import { canonicalizeOperationalAddress } from '@/lib/operational-address';

export interface ParsedIfoodOrder {
  orderId:string; ifoodId:string; confirmationCode:string; customerName:string;
  phone:string; address:string; mapsLink:string; isPaid:boolean;
  paymentMethod:Delivery['payment_method']|null; value:string; customerCharge:string;
  subsidy:string; changeFor:string; drinks:string[]; observations:string[];
  routeNumber:string; motoboyHint:string;
}

const STREET=/(?:\br\.(?=\s)|\b(?:rua|av\.?|avenida|alameda|travessa|pra[cç]a|rodovia|estrada|beco|viela)\b)/i;
const URL=/https?:\/\/[^\s<>()]+/gi;
const MAP_HOST=/(?:google\.[^/]+\/(?:maps|url)|maps\.google\.[^/]+|maps\.app\.goo\.gl|goo\.gl\/maps)/i;
const OBS_PREFIX=/^(?:obs(?:erva(?:ç|c)[aã]o)?|observa[cç][oõ]es?|refer[eê]ncia|complemento|instru(?:ç|c)[aã]o|instru[cç][oõ]es?|port[aã]o|nota)\s*:\s*/i;
const INSTRUCTION=/\b(?:ap(?:to|artamento)?\.?|bloco|casa|fundos|andar|sala|lote|quadra|port[aã]o|interfone|ligar|chamar|entrada|esquina|em frente|ao lado|casa de|deixar|tocar|buzinar|sem cebola|sem salada|retirar|adicionar|caprichar|separar|mandar|enviar)\b/i;
const emptyResult=():ParsedIfoodOrder=>({orderId:'',ifoodId:'',confirmationCode:'',customerName:'',phone:'',address:'',mapsLink:'',isPaid:false,paymentMethod:null,value:'',customerCharge:'',subsidy:'',changeFor:'',drinks:[],observations:[],routeNumber:'',motoboyHint:''});
const spaces=(v:string)=>v.replace(/\s+/g,' ').replace(/\s+,/g,',').trim();
const numberValue=(v:string)=>{const c=v.replace(/\s/g,'');return Number(c.includes(',')?c.replace(/\./g,'').replace(',','.'):c)};
const currency=(v:number)=>v.toFixed(2).replace('.',',');
function addUnique(target:string[],value:string){const clean=spaces(value).replace(/^[-–—,;]+|[-–—,;]+$/g,'').trim();const key=clean.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(clean&&!target.some(x=>x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()===key))target.push(clean)}
function mapUrl(line:string){return(line.match(URL)??[]).find(v=>MAP_HOST.test(v))?.replace(/[),.;]+$/,'')??''}
function idTokens(line:string){if(STREET.test(line)||/\b(?:cep|total)\b|r\$/i.test(line))return[];return line.replace(/\D+/g,' ').trim().split(' ').filter(Boolean)}
function cleanAddress(source:string,obs:string[]){const n=canonicalizeOperationalAddress(source);n.observations.forEach(x=>addUnique(obs,x));return n.address}
function parsePayment(line:string,r:ParsedIfoodOrder){const neg=/\b(?:n[aã]o\s+pago|pagamento\s+pendente|pix\s+pendente|pagar\s+na\s+entrega)\b/i.test(line);const cash=/\b(?:dinheiro|troco|voltar)\b/i.test(line);const card=/\b(?:cart[aã]o|cr[eé]dito|d[eé]bito|maquininha)\b/i.test(line);const paid=!neg&&!cash&&!card&&/\b(?:pago|paga|pagamento\s+(?:online|pago|confirmado|aprovado|ok)|pedido\s+pago|j[aá]\s+pago|pago\s+(?:no\s+app|online)|pix\s+(?:pago|confirmado|aprovado|ok))\b/i.test(line);if(card){r.paymentMethod='cartao';r.isPaid=false;r.changeFor='';return}if(cash){r.paymentMethod='dinheiro';r.isPaid=false;return}if(paid){r.paymentMethod='pix';r.isPaid=true;r.changeFor='';return}if(/\bpix\b/i.test(line)){r.paymentMethod='pix';r.isPaid=!neg&&/\b(?:pago|confirmado|aprovado|ok|online)\b/i.test(line)}}
function parseRouteHint(line:string,r:ParsedIfoodOrder){const m=line.match(/\brota\s*(?:n[ºo°.]?\s*)?(\d{1,2})\b/i);if(m)r.routeNumber||=m[1];const x=line.match(/\b(?:motoboy|entregador)\s*[:\-]?\s*([A-Za-zÀ-ÿ][A-Za-zÀ-ÿ' -]{1,40})$/i);if(x)r.motoboyHint||=spaces(x[1])}
function parseFinancial(line:string,r:ParsedIfoodOrder){
  const explicit=line.match(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)\s*(?:[,;|-]\s*)?(?:em\s+)?(?:dinheiro\s*)?(?:com\s+)?troco\s+(?:para|p\/?|de)\s*(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i);
  if(explicit){const base=numberValue(explicit[1]), tendered=numberValue(explicit[2]);if(Number.isFinite(base)){r.customerCharge||=currency(base);r.value||=currency(base)}if(Number.isFinite(tendered))r.changeFor=currency(tendered)}
  const tokens=[...line.matchAll(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/gi)].map(m=>({value:numberValue(m[1]),index:m.index??0}));
  const changeIndex=line.search(/\b(?:troco|voltar)\b/i);const baseToken=tokens.find(t=>changeIndex<0||t.index<changeIndex);
  if(!r.customerCharge&&/\b(?:valor|pagamento|pago|pix|cart[aã]o|dinheiro|troco|voltar|cobrar|cliente\s+paga)\b/i.test(line)&&baseToken&&Number.isFinite(baseToken.value)){r.customerCharge=currency(baseToken.value);r.value||=r.customerCharge}
  const base=r.customerCharge?numberValue(r.customerCharge):baseToken?.value;
  const tendered=line.match(/\btroco\s+(?:para|p\/?|de)\s*(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i);
  const returned=line.match(/\b(?:troco|voltar)\s*(?!para\b|p\/?\b|de\b)(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i)||line.match(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)\s+de\s+troco\b/i);
  if(!r.changeFor&&tendered){const v=numberValue(tendered[1]);if(Number.isFinite(v))r.changeFor=currency(v)}else if(!r.changeFor&&returned&&Number.isFinite(base)){const v=numberValue(returned[1]);if(Number.isFinite(v))r.changeFor=currency((base as number)+v)}
  const subsidy=line.match(/\b(?:cupom|subs[ií]dio|desconto\s+ifood|ifood\s+paga|ifood\s+subsidia)\s*[:\-]?\s*(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i)||line.match(/(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)\s*(?:de\s+)?(?:cupom|subs[ií]dio)\b/i);
  if(subsidy){const v=numberValue(subsidy[1]);if(Number.isFinite(v)&&v>=0){r.subsidy=currency(v);if(r.customerCharge){const c=numberValue(r.customerCharge);if(Number.isFinite(c))r.value=currency(c+v)}}}
  const total=line.match(/\b(?:valor\s+total|total\s+do\s+pedido|total)\s*[:\-]?\s*(?:r\$\s*)?(\d+(?:[.,]\d{1,2})?)/i);if(total&&!/\btroco\b/i.test(line)){const v=numberValue(total[1]);if(Number.isFinite(v)){r.value=currency(v);if(!r.customerCharge&&!r.subsidy)r.customerCharge=r.value}}
}
export function parseIfoodOrderText(text:string):ParsedIfoodOrder{const r=emptyResult();const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let idLine=-1;lines.forEach((line,i)=>{const url=mapUrl(line);if(url)r.mapsLink=url;const tokens=idTokens(line);if(!tokens.some(t=>t.length===8))return;if(idLine<0)idLine=i;r.ifoodId||=tokens.find(t=>t.length===8)??'';const short=tokens.filter(t=>t.length===4||t.length===5);r.orderId||=short[0]??'';r.confirmationCode||=short.find(t=>t.length===4&&t!==r.orderId)??''});lines.forEach((original,i)=>{const line=spaces(original.replace(URL,' '));if(!line||i===idLine)return;if(/^(?:cliente|nome)\s*:/i.test(line)){r.customerName=line.replace(/^(?:cliente|nome)\s*:\s*/i,'').trim();return}if(!r.customerName&&idLine>=0&&i>idLine&&i<=idLine+2&&!STREET.test(line)&&!/(?:cep|pago|cart[aã]o|dinheiro|pix|total|cupom|subs[ií]dio)/i.test(line)&&!/\d+[.,]\d{2}/.test(line)){r.customerName=line.replace(/^[-•*]\s*/,'').trim();return}const phone=line.match(/(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4,5}[-\s]?\d{4}/)?.[0];if(phone&&!r.phone&&!/cep/i.test(line)){const d=phone.replace(/\D/g,'');if(d.length>=10&&d.length<=11)r.phone=d}const drink=/(coca|guaran[aá]|fanta|sprite|suco|refrigerante|cerveja|heineken|[aá]gua|schweppes|del valle)/i.test(line),volume=/(\d+\s*(?:l|ml|litro|litros)|lata|garrafa)/i.test(line);if(drink||(volume&&!STREET.test(line)&&!/\bap(?:to)?\b/i.test(line))){addUnique(r.drinks,line.replace(/^[-•*x\d\s]+\s*/i,''));return}parseRouteHint(line,r);parsePayment(line,r);parseFinancial(line,r);if(r.routeNumber&&/\brota\b/i.test(line))return;if(STREET.test(line)||/\bCEP\s*:?\s*\d{5}-?\d{3}\b/i.test(line)){r.address=cleanAddress(original,r.observations);return}if(OBS_PREFIX.test(line)){addUnique(r.observations,line.replace(OBS_PREFIX,''));return}if(INSTRUCTION.test(line)&&!/(?:pagamento|dinheiro|troco|cart[aã]o|pix|cupom|subs[ií]dio)/i.test(line))addUnique(r.observations,line)});if(!r.customerCharge&&r.value)r.customerCharge=r.value;if(r.subsidy&&r.customerCharge){const a=numberValue(r.customerCharge),b=numberValue(r.subsidy);if(Number.isFinite(a)&&Number.isFinite(b))r.value=currency(a+b)}return r}
export function parseIfoodOrdersText(text:string):ParsedIfoodOrder[]{const lines=text.split(/\r?\n/);const headers=lines.map((line,index)=>({index,tokens:idTokens(line)})).filter(x=>x.tokens.some(t=>t.length===8)).map(x=>x.index);if(headers.length<=1)return[parseIfoodOrderText(text)];const shared=parseIfoodOrderText(text);return headers.map((start,pos)=>{const end=headers[pos+1]??lines.length;const parsed=parseIfoodOrderText(lines.slice(start,end).join('\n'));return{...parsed,address:parsed.address||shared.address,mapsLink:parsed.mapsLink||shared.mapsLink,phone:parsed.phone||shared.phone,routeNumber:parsed.routeNumber||shared.routeNumber,motoboyHint:parsed.motoboyHint||shared.motoboyHint,observations:parsed.observations.length?parsed.observations:[...shared.observations]}})}
