import type { Route, Delivery, Customer } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Marcos Vinícius',
    neighborhood: 'Nossa Senhora de Fátima',
    last_confirmation_code: '4821',
  },
  {
    id: 'cust-2',
    name: 'Fernanda Rezende',
    neighborhood: 'Alto da Colina',
    last_confirmation_code: '1093',
  },
  {
    id: 'cust-3',
    name: 'João Pedro Almeida',
    neighborhood: 'Jardim Panorama',
    last_confirmation_code: '5567',
  },
  {
    id: 'cust-4',
    name: 'Camila Ferreira',
    neighborhood: 'Nossa Senhora de Fátima',
    last_confirmation_code: '3320',
  },
  {
    id: 'cust-5',
    name: 'Rafael Souza',
    neighborhood: 'Vila Rica',
    last_confirmation_code: '7712',
  },
];

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    name: 'Rota 1',
    status: 'aberta',
    motoboy_name: 'Wesley',
    departure_time: new Date().toISOString(),
    change_money: 50,
    drinks_summary: '2 coca lata, 1 guaraná 2L',
  },
  {
    id: 'route-2',
    name: 'Rota 2',
    status: 'aberta',
    motoboy_name: 'Douglas',
    departure_time: new Date().toISOString(),
    change_money: 100,
    drinks_summary: '1 fanta laranja lata',
  },
  {
    id: 'route-3',
    name: 'Rota 3',
    status: 'fechada',
    motoboy_name: 'Wesley',
    departure_time: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    change_money: 30,
  },
];

export const mockDeliveries: Delivery[] = [
  {
    id: 'del-1',
    route_id: 'route-1',
    order_id: '84920157',
    confirmation_code: '4821',
    customer_id: 'cust-1',
    value: 47.9,
    is_paid: false,
    payment_method: 'dinheiro',
    change_for: 50,
    address_string: 'Rua Antônio Fonseca, 145, Nossa Senhora de Fátima',
    maps_link: 'https://maps.google.com/?q=Rua+Antonio+Fonseca+145+Patos+de+Minas',
    observation: 'Portão azul, casa dos fundos',
    drinks: '1 coca lata',
  },
  {
    id: 'del-2',
    route_id: 'route-1',
    order_id: '19283746',
    confirmation_code: '3320',
    customer_id: 'cust-4',
    value: 62.5,
    is_paid: true,
    payment_method: 'pix',
    address_string: 'Av. Getúlio Vargas, 890, Nossa Senhora de Fátima',
    maps_link: 'https://maps.google.com/?q=Av+Getulio+Vargas+890+Patos+de+Minas',
    drinks: '1 guaraná lata',
  },
  {
    id: 'del-3',
    route_id: 'route-2',
    order_id: '55012893',
    confirmation_code: '1093',
    customer_id: 'cust-2',
    value: 38.0,
    is_paid: false,
    payment_method: 'cartao_credito',
    address_string: 'Rua das Palmeiras, 22, Alto da Colina',
    maps_link: 'https://maps.google.com/?q=Rua+das+Palmeiras+22+Patos+de+Minas',
    observation: 'Cuidado com o cachorro',
  },
  {
    id: 'del-4',
    route_id: 'route-2',
    order_id: '77341902',
    confirmation_code: '7712',
    customer_id: 'cust-5',
    value: 29.9,
    is_paid: false,
    payment_method: 'dinheiro',
    change_for: 100,
    address_string: 'Rua São José, 501, Vila Rica',
    maps_link: 'https://maps.google.com/?q=Rua+Sao+Jose+501+Patos+de+Minas',
    drinks: '1 fanta laranja lata',
  },
];
