// app/abastecimentos/detalhes/page.tsx
'use client';
import { Suspense, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { CalendarDays, CheckCircle2, Download, Edit3, Store, Trash2, Undo2, UserRound, Wallet } from 'lucide-react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/layout/PageHeader';
import { useAppStore } from '@/store/useAppStore';
import { money, SUPPLY_STATUS_LABELS, supplyTotal } from '@/lib/stock-supply';
import { ShoppingSession } from '@/components/stock-supplies/ShoppingSession';
import { downloadShoppingListPdf } from '@/lib/shopping-list-pdf';

function Content() {
  const router = useRouter(); const id = useSearchParams().get('id');
  const supply = useAppStore((state) => state.stockSupplies.find((item) => item.id === id));
  const update = useAppStore((state) => state.updateStockSupply); const remove = useAppStore((state) => state.deleteStockSupply); const integrate = useAppStore((state) => state.integrateStockSupply); const reverse = useAppStore((state) => state.reverseStockSupply);
  const [busy, setBusy] = useState(false);
  if (!supply) return <PageHeader title="Compra não encontrada" to="/abastecimentos"/>;
  const advance = async () => {
    const next = supply.status === 'solicitado' ? 'em_compra' : supply.status === 'em_compra' ? 'recebido' : supply.status === 'recebido' ? 'conferido' : null;
    if (!next) return; setBusy(true);
    try { const now = new Date().toISOString(); await update(supply.id, { status: next, shopping_started_at:next==='em_compra'?now:supply.shopping_started_at, received_at: next === 'recebido' ? now : supply.received_at, checked_at: next === 'conferido' ? now : supply.checked_at }); toast.success(`Status: ${SUPPLY_STATUS_LABELS[next]}.`); } finally { setBusy(false); }
  };
  const deleteRecord = async () => { if (!confirm('Excluir esta compra permanentemente?')) return; setBusy(true); try { await remove(supply.id); toast.success('Registro excluído.'); router.replace('/abastecimentos'); } catch { toast.error('Não foi possível excluir.'); setBusy(false); } };
  const checkIn = async () => { setBusy(true); try { await integrate(supply.id); toast.success('Compra conferida e estoque atualizado.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível integrar ao estoque.'); } finally { setBusy(false); } };
  const reverseIntegration = async () => { if(!confirm('Estornar todas as entradas desta compra? A operação ficará registrada no histórico.'))return;setBusy(true);try{await reverse(supply.id);toast.success('Integração estornada com histórico preservado.')}catch(error){toast.error(error instanceof Error?error.message:'Não foi possível estornar.')}finally{setBusy(false)} };
  const finishShopping=async(items:typeof supply.items)=>{setBusy(true);try{const now=new Date().toISOString(),products_amount=Number(items.reduce((sum,item)=>sum+(item.total_price||0),0).toFixed(2));await update(supply.id,{items,products_amount,total_amount:Number((products_amount+(supply.transport_amount||0)+(supply.other_costs||0)).toFixed(2)),status:'recebido',received_at:now,shopping_completed_at:now});toast.success('Compra finalizada. Agora confira a entrada no estoque.')}finally{setBusy(false)}};
  return <div className="pb-28">
    <PageHeader title="Detalhes da compra" subtitle={SUPPLY_STATUS_LABELS[supply.status]} to="/abastecimentos"/>
    <section className="rounded-[28px] border border-amber-500/20 bg-amber-500/[.05] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-amber-400">Total registrado</p><p className="mt-2 font-heading text-3xl font-black text-zinc-100">{money(supplyTotal(supply))}</p></div><span className="rounded-full bg-amber-500/10 px-3 py-2 text-[10px] font-black text-amber-400">{SUPPLY_STATUS_LABELS[supply.status]}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs text-zinc-400"><p className="flex gap-2"><UserRound size={15}/>{supply.purchaser_name || 'Comprador não informado'}</p><p className="flex gap-2"><Store size={15}/>{supply.supplier || 'Fornecedor não informado'}</p><p className="flex gap-2"><CalendarDays size={15}/>{new Date(supply.occurred_at).toLocaleString('pt-BR')}</p><p className="flex gap-2"><Wallet size={15}/>{supply.payment_method || 'Pagamento não informado'}</p></div></section>
    <section className="mt-5 space-y-3"><h2 className="font-heading text-base font-black text-zinc-100">Itens ({supply.items.length})</h2>{supply.items.map((item) => <article key={item.id} className="rounded-[22px] border border-zinc-800 bg-zinc-900/50 p-4"><div className="flex justify-between gap-3"><div><p className="font-black text-zinc-100">{item.name}</p>{item.presentation_label&&<p className="mt-1 text-[10px] font-bold text-amber-400">{item.purchase_quantity?.toLocaleString('pt-BR')} × {item.presentation_label}</p>}<p className="mt-1 text-xs text-zinc-500">Entrada: {item.quantity.toLocaleString('pt-BR')} {item.unit}{item.unit_price?` · ${money(item.unit_price)} por ${item.unit}`:''}</p><p className={`mt-2 text-[10px] font-bold ${item.stock_product_id?'text-emerald-400':'text-amber-400'}`}>{item.stock_product_id?'Vinculado ao estoque':'Vínculo pendente'}</p></div><p className="font-black text-emerald-400">{item.total_price ? money(item.total_price) : 'Sem preço'}</p></div></article>)}</section>
    <section className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-zinc-900/50 p-3"><p className="text-[9px] text-zinc-600">Produtos</p><p className="mt-1 text-xs font-black text-zinc-200">{money(supply.products_amount)}</p></div><div className="rounded-2xl bg-zinc-900/50 p-3"><p className="text-[9px] text-zinc-600">Uber / frete</p><p className="mt-1 text-xs font-black text-zinc-200">{money(supply.transport_amount || 0)}</p></div><div className="rounded-2xl bg-zinc-900/50 p-3"><p className="text-[9px] text-zinc-600">Outros</p><p className="mt-1 text-xs font-black text-zinc-200">{money(supply.other_costs || 0)}</p></div></section>
    {supply.observation && <section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900/45 p-4"><p className="text-[10px] font-black uppercase text-zinc-600">Observação</p><p className="mt-2 text-sm text-zinc-300">{supply.observation}</p></section>}
    {supply.status==='em_compra'&&<ShoppingSession supply={supply} onFinish={finishShopping} busy={busy}/>}
    {supply.status!=='em_compra'&&<button onClick={()=>downloadShoppingListPdf(supply)} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-xl border border-zinc-700 text-sm font-bold text-zinc-300"><Download size={17}/>Baixar lista em PDF</button>}
    {!supply.stock_integrated_at&&<div className="mt-6 grid grid-cols-2 gap-2"><button onClick={() => router.push(`/abastecimentos/editar?id=${supply.id}`)} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-zinc-800 text-sm font-bold text-zinc-200"><Edit3 size={16}/>Editar</button><button onClick={deleteRecord} disabled={busy} className="flex h-12 items-center justify-center gap-2 rounded-xl border border-red-500/20 text-sm font-bold text-red-400"><Trash2 size={16}/>Excluir</button></div>}
    {supply.stock_reversed_at?<div className="mt-6 rounded-2xl border border-amber-500/25 bg-amber-500/[.06] p-4 text-sm font-bold text-amber-400">Integração estornada. O histórico foi preservado.</div>:supply.stock_integrated_at?<><div className="mt-6 rounded-2xl border border-emerald-500/25 bg-emerald-500/[.06] p-4 text-sm font-bold text-emerald-400">Compra integrada ao estoque com proteção transacional.</div><button onClick={reverseIntegration} disabled={busy} className="mt-3 flex h-12 w-full items-center justify-center gap-2 rounded-xl border border-amber-500/25 text-sm font-bold text-amber-400"><Undo2 size={17}/>Estornar integração</button></>:(supply.status==='recebido'||supply.status==='conferido')?<button onClick={checkIn} disabled={busy} className="mt-3 flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-emerald-500 font-black text-zinc-950"><CheckCircle2 size={18}/>Conferir e lançar no estoque</button>:supply.status==='solicitado'?<button onClick={advance} disabled={busy} className="mt-3 flex h-14 w-full items-center justify-center gap-2 rounded-2xl bg-emerald-500 font-black text-zinc-950"><CheckCircle2 size={18}/>Iniciar compra</button>:null}
  </div>;
}
export default function StockSupplyDetailsPage() { return <Suspense fallback={<p className="py-20 text-center text-zinc-500">Carregando...</p>}><Content/></Suspense>; }
