// app/motoboys/acerto/page.tsx
'use client';
import { Suspense,useMemo,useState } from 'react';import { useSearchParams } from 'next/navigation';import { ArrowDownLeft,ArrowUpRight,Banknote,CalendarDays,ChevronLeft,ChevronRight,Info,Package,Plus,Send,Trash2,X } from 'lucide-react';import { toast } from 'sonner';import { PageHeader } from '@/components/layout/PageHeader';import { useAppStore } from '@/store/useAppStore';import { getMotoboyDayData,operationalDateKey,type ValeInput } from '@/lib/motoboy-analytics';
const fromKey=(key:string)=>new Date(`${key}T12:00:00-03:00`);const shift=(key:string,days:number)=>{const date=fromKey(key);date.setDate(date.getDate()+days);return operationalDateKey(date);};const money=(value:number)=>value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function Content(){const id=useSearchParams().get('id');const motoboy=useAppStore(state=>state.motoboys.find(item=>item.id===id));const routes=useAppStore(state=>state.routes);const deliveries=useAppStore(state=>state.deliveries);const [date,setDate]=useState(()=>operationalDateKey(new Date()));const [month,setMonth]=useState(()=>fromKey(operationalDateKey(new Date())));const [calendar,setCalendar]=useState(false);const [vales,setVales]=useState<ValeInput[]>([]);const [valeDescription,setValeDescription]=useState('');const [valeValue,setValeValue]=useState('');const [cashHandedOver,setCashHandedOver]=useState(true);const data=useMemo(()=>motoboy?getMotoboyDayData(motoboy,date,routes,deliveries,vales,cashHandedOver):null,[cashHandedOver,date,deliveries,motoboy,routes,vales]);const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const start=new Date(first.getFullYear(),first.getMonth(),1-first.getDay());return Array.from({length:42},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return day;});},[month]);if(!motoboy||!data)return <div><PageHeader title="Acerto indisponível" to="/motoboys"/></div>;
  const addVale=()=>{const amount=Number(valeValue.replace(/\./g,'').replace(',','.'));if(!valeDescription.trim()||!Number.isFinite(amount)||amount<=0){toast.error('Informe descrição e valor do vale.');return;}setVales(current=>[...current,{id:String(Date.now()),description:valeDescription.trim(),amount}]);setValeDescription('');setValeValue('');};
  const copy=async()=>{const [year,monthValue,day]=date.split('-');let text=`ACERTO DFL ENTREGAS\nEntregador: ${motoboy.name}\nData: ${day}/${monthValue}/${year}\n\nEntregas concluídas: ${data.deliveries.length}\nRotas finalizadas: ${data.completedRoutes}\nDiária: R$ ${money(data.fee.amount)}\n${data.fee.description}\nVales: R$ ${money(data.totalVales)}\nDiária líquida: R$ ${money(data.liquidFee)}\nDinheiro líquido recolhido: R$ ${money(data.cashCollected)}\n\n${data.mustReturn?'MOTOBOY DEVOLVE À LOJA':'LOJA PAGA AO MOTOBOY'}: R$ ${money(data.balance)}`;await navigator.clipboard.writeText(text);toast.success('Acerto copiado para o WhatsApp.');};
  return <div className="flex flex-col gap-5 pb-28"><PageHeader title="Acerto de caixa" subtitle={motoboy.name} to={`/motoboys/details?id=${motoboy.id}`}/><div className="flex items-center gap-2 rounded-[22px] border border-zinc-800 bg-zinc-900/45 p-2"><button onClick={()=>setDate(value=>shift(value,-1))} className="date-button"><ChevronLeft/></button><button onClick={()=>{setMonth(fromKey(date));setCalendar(true);}} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-2xl bg-zinc-800 text-sm font-black"><CalendarDays size={17} className="text-emerald-400"/>{fromKey(date).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'}).replaceAll('.','')}</button><button onClick={()=>setDate(value=>shift(value,1))} className="date-button"><ChevronRight/></button></div>
  {!motoboy.payment_rule&&<div className="flex gap-3 rounded-2xl border border-amber-500/25 bg-amber-500/5 p-4"><Info size={18} className="shrink-0 text-amber-400"/><div><p className="text-sm font-bold text-amber-300">Pagamento não configurado</p><p className="mt-1 text-xs text-zinc-500">A diária ficará em zero até a regra ser cadastrada em Editar.</p></div></div>}
  <div className="grid grid-cols-2 gap-3"><Card icon={Package} label="Entregas concluídas" value={String(data.deliveries.length)} tone="sky"/><Card icon={Banknote} label="Dinheiro líquido" value={`R$ ${money(data.cashCollected)}`} tone="amber"/></div>
  <section className="rounded-[24px] border border-sky-500/20 bg-sky-500/5 p-5"><p className="text-[10px] font-black uppercase tracking-wider text-sky-400">Diária calculada</p><p className="mt-2 text-2xl font-black text-sky-300">R$ {money(data.fee.amount)}</p><p className="mt-1 text-xs text-zinc-400">{data.fee.description}</p>{vales.length>0&&<div className="mt-4 space-y-2 border-t border-sky-500/10 pt-3">{vales.map(vale=><div key={vale.id} className="flex items-center justify-between text-xs"><span className="text-zinc-400">{vale.description}</span><div className="flex items-center gap-3"><span className="font-bold text-red-400">- R$ {money(vale.amount)}</span><button onClick={()=>setVales(current=>current.filter(item=>item.id!==vale.id))}><Trash2 size={13} className="text-red-500"/></button></div></div>)}</div>}<div className="mt-4 flex items-center justify-between border-t border-sky-500/10 pt-3"><span className="text-xs font-bold text-zinc-400">Líquido da diária</span><span className="font-black text-sky-300">R$ {money(data.liquidFee)}</span></div></section>
  <section><p className="mb-2 px-1 text-[10px] font-black uppercase tracking-wider text-zinc-500">Vale temporário</p><div className="grid grid-cols-[1fr_100px_48px] gap-2"><input value={valeDescription} onChange={event=>setValeDescription(event.target.value)} placeholder="Descrição" className="input"/><input value={valeValue} onChange={event=>setValeValue(event.target.value)} inputMode="decimal" placeholder="0,00" className="input"/><button onClick={addVale} className="flex h-12 items-center justify-center rounded-xl bg-zinc-800"><Plus size={18}/></button></div><p className="mt-2 px-1 text-[10px] text-zinc-600">Os vales desta simulação não são salvos e somem ao sair.</p></section>
  <label className="flex items-center justify-between rounded-2xl border border-zinc-800 bg-zinc-900/45 p-4"><div><p className="text-sm font-bold">Dinheiro já entregue ao caixa</p><p className="text-[10px] text-zinc-500">Desative se o valor ainda estiver com o motoboy</p></div><input type="checkbox" checked={cashHandedOver} onChange={event=>setCashHandedOver(event.target.checked)} className="h-5 w-5 accent-emerald-500"/></label>
  <section className={`rounded-[26px] p-5 ${data.mustReturn?'bg-amber-500':'bg-emerald-500'}`}><div className="flex items-center justify-between text-zinc-950"><p className="text-[10px] font-black uppercase tracking-wider">Resultado do acerto</p>{data.mustReturn?<ArrowDownLeft/>:<ArrowUpRight/>}</div><p className="mt-1 text-3xl font-black text-zinc-950">R$ {money(data.balance)}</p><p className="mt-1 text-xs font-black text-zinc-900">{data.mustReturn?'MOTOBOY DEVOLVE À LOJA':'LOJA PAGA AO MOTOBOY'}</p></section>
  <button onClick={copy} className="flex h-14 items-center justify-center gap-2 rounded-2xl bg-zinc-100 font-black text-zinc-950"><Send size={17}/>Copiar acerto</button>
  {calendar&&<div className="fixed inset-0 z-50 flex items-end bg-black/75 p-3 backdrop-blur-sm" onClick={()=>setCalendar(false)}><div className="w-full rounded-[30px] border border-zinc-800 bg-zinc-950 p-5" onClick={event=>event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><button onClick={()=>setMonth(value=>new Date(value.getFullYear(),value.getMonth()-1,1))} className="date-button"><ChevronLeft/></button><p className="font-black capitalize">{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</p><button onClick={()=>setMonth(value=>new Date(value.getFullYear(),value.getMonth()+1,1))} className="date-button"><ChevronRight/></button></div><div className="grid grid-cols-7 text-center text-[10px] text-zinc-600">{['D','S','T','Q','Q','S','S'].map((label,index)=><span key={`${label}-${index}`}>{label}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{days.map(day=>{const key=operationalDateKey(day);return <button key={key} onClick={()=>{setDate(key);setCalendar(false);}} className={`aspect-square rounded-xl text-xs font-bold ${key===date?'bg-emerald-500 text-zinc-950':day.getMonth()===month.getMonth()?'text-zinc-300':'text-zinc-700'}`}>{day.getDate()}</button>})}</div><button onClick={()=>setCalendar(false)} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-zinc-900 text-xs font-bold text-zinc-400"><X size={15}/>Fechar</button></div></div>}
  <style jsx>{`.date-button{display:flex;height:2.75rem;width:2.75rem;align-items:center;justify-content:center;border-radius:1rem;color:rgb(113 113 122)}.input{height:3rem;min-width:0;border-radius:.75rem;border:1px solid rgb(39 39 42);background:rgb(24 24 27/.6);padding:0 .75rem;font-size:.75rem;outline:none}`}</style></div>;
}
function Card({icon:Icon,label,value,tone}:{icon:typeof Package;label:string;value:string;tone:'sky'|'amber'}){return <div className={`rounded-[22px] border p-4 ${tone==='sky'?'border-sky-500/20 bg-sky-500/5':'border-amber-500/20 bg-amber-500/5'}`}><Icon size={16} className={tone==='sky'?'text-sky-400':'text-amber-400'}/><p className="mt-3 text-xl font-black">{value}</p><p className="text-[10px] text-zinc-500">{label}</p></div>;}
export default function MotoboySettlementPage(){return <Suspense fallback={<p className="py-20 text-center text-zinc-500">Carregando...</p>}><Content/></Suspense>;}
