// components/store/PerformanceModals.tsx
'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Banknote, Bike, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, CreditCard, Eye, EyeOff, Filter, MapPin, Package, QrCode, Receipt, Store, UserRound, Wallet, X } from 'lucide-react';
import type { StoreDashboardData } from '@/hooks/useStoreDashboard';
import { deliveryDate, OPERATION_TIME_ZONE, routeDate, routeStartedAt } from '@/lib/operational-time';
import type { Delivery } from '@/types';

interface Props { isLogisticsOpen:boolean;closeLogistics:()=>void;isRevenueOpen:boolean;closeRevenue:()=>void;isPrivacyMode:boolean;togglePrivacyMode:()=>void;dashboardData:StoreDashboardData; }
type PaymentFilter='all'|'pix'|'dinheiro'|'cartao';
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const time=(value?:string)=>value?new Date(value).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',timeZone:OPERATION_TIME_ZONE}):'--:--';
const payment=(delivery:Delivery)=>delivery.is_paid?'Pago no app':delivery.payment_method==='dinheiro'?'Dinheiro':delivery.payment_method?.startsWith('cartao')?'Cartão':'Pix';

export function PerformanceModals(props:Props){
  return <>{props.isLogisticsOpen&&<Logistics {...props}/>} {props.isRevenueOpen&&<Revenue {...props}/>}</>;
}

function DateBar({data,tone}:{data:StoreDashboardData;tone:'sky'|'green'}){const color=tone==='sky'?'text-sky-400 bg-sky-500/10 border-sky-500/20':'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';return <div className="flex items-center gap-2"><button onClick={data.goToPreviousDay} className="flex h-10 w-10 items-center justify-center rounded-xl border border-zinc-800 bg-zinc-900"><ChevronLeft size={18}/></button><div className={`flex h-10 min-w-0 flex-1 items-center justify-center gap-2 rounded-xl border text-xs font-black ${color}`}><CalendarDays size={15}/>{data.formattedDateLabel}</div><button onClick={data.goToNextDay} className="flex h-10 w-10 items-center justify-center rounded-xl border border-zinc-800 bg-zinc-900"><ChevronRight size={18}/></button></div>;}
function Header({title,subtitle,icon:Icon,onClose,tone}:{title:string;subtitle:string;icon:typeof Bike;onClose:()=>void;tone:'sky'|'green'}){return <header className="flex items-center gap-3"><button onClick={onClose} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-zinc-800 bg-zinc-900 text-zinc-300 active:scale-95" aria-label="Voltar para Loja"><ChevronLeft size={20}/></button><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${tone==='sky'?'bg-sky-500/10 text-sky-400':'bg-emerald-500/10 text-emerald-400'}`}><Icon size={20}/></div><div className="min-w-0 flex-1"><h2 className="truncate font-heading text-xl font-black">{title}</h2><p className="truncate text-xs text-zinc-500">{subtitle}</p></div><button onClick={onClose} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-zinc-900 text-zinc-400 active:scale-95" aria-label="Fechar"><X size={18}/></button></header>;}

function Logistics(props:Props){
  const router=useRouter();const data=props.dashboardData;const [motoboy,setMotoboy]=useState('all');
  const names=useMemo(()=>Array.from(new Set(data.selectedDateRoutes.map(route=>route.motoboy_name))).sort((a,b)=>a.localeCompare(b,'pt-BR')),[data.selectedDateRoutes]);
  const routes=useMemo(()=>data.selectedDateRoutes.filter(route=>motoboy==='all'||route.motoboy_name===motoboy).sort((a,b)=>new Date(routeDate(a)||0).getTime()-new Date(routeDate(b)||0).getTime()),[data.selectedDateRoutes,motoboy]);
  const deliveryCount=routes.reduce((sum,route)=>sum+data.selectedDateDeliveries.filter(delivery=>delivery.route_id===route.id).length,0);
  return <div className="fixed inset-0 z-[110] overflow-y-auto bg-zinc-950"><div className="sticky top-0 z-10 space-y-4 border-b border-zinc-800 bg-zinc-950/95 p-4 backdrop-blur-xl"><Header title="Resumo de rotas" subtitle="O caminho da operação neste dia" icon={Bike} onClose={props.closeLogistics} tone="sky"/><DateBar data={data} tone="sky"/></div><main className="space-y-5 p-4 pb-32">
    <div className="grid grid-cols-3 gap-2"><Stat value={routes.length} label="Rotas"/><Stat value={deliveryCount} label="Entregas"/><Stat value={routes.filter(route=>route.status==='fechada').length} label="Finalizadas" tone="green"/></div>
    {names.length>1&&<div className="flex gap-2 overflow-x-auto pb-1">{['all',...names].map(name=><button key={name} onClick={()=>setMotoboy(name)} className={`shrink-0 rounded-xl px-3.5 py-2 text-xs font-bold ${motoboy===name?'bg-zinc-100 text-zinc-950':'border border-zinc-800 bg-zinc-900 text-zinc-400'}`}><UserRound size={12} className="mr-1 inline"/>{name==='all'?'Equipe toda':name}</button>)}</div>}
    <div className="space-y-3">{routes.map((route,index)=>{const deliveries=data.selectedDateDeliveries.filter(item=>item.route_id===route.id);const completed=deliveries.filter(item=>item.completed).length;return <button key={route.id} onClick={()=>router.push(`/rotas/details?id=${route.id}`)} className="w-full rounded-[24px] border border-zinc-800 bg-zinc-900/50 p-4 text-left"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-sky-500/10 text-sm font-black text-sky-400">{index+1}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate font-black">{route.name}</p><span className={`rounded-md px-2 py-1 text-[9px] font-black uppercase ${route.status==='fechada'?'bg-emerald-500/10 text-emerald-400':routeStartedAt(route)?'bg-sky-500/10 text-sky-400':'bg-zinc-800 text-zinc-400'}`}>{route.status==='fechada'?'Finalizada':routeStartedAt(route)?'Na rua':'Montando'}</span></div><p className="mt-1 text-xs text-zinc-500"><UserRound size={11} className="mr-1 inline"/>{route.motoboy_name}</p></div></div><div className="mt-4 grid grid-cols-3 border-t border-zinc-800 pt-3 text-center"><Small value={`${completed}/${deliveries.length}`} label="Entregas"/><Small value={time(routeStartedAt(route)||routeDate(route))} label={routeStartedAt(route)?'Saída':'Criada'}/><Small value={money(deliveries.reduce((sum,item)=>sum+(item.value||0),0))} label="Valor"/></div></button>;})}{!routes.length&&<Empty icon={Bike} text="Nenhuma rota nesta data."/>}</div>
  </main></div>;
}

function Revenue(props:Props){
  const router=useRouter();const data=props.dashboardData;const [filter,setFilter]=useState<PaymentFilter>('all');
  const rows=useMemo(()=>data.selectedDateOrders.filter(item=>filter==='all'||(filter==='cartao'?item.payment_method?.startsWith('cartao'):item.payment_method===filter)).sort((a,b)=>new Date(deliveryDate(a)||0).getTime()-new Date(deliveryDate(b)||0).getTime()),[data.selectedDateOrders,filter]);
  const hidden=(value:number)=>props.isPrivacyMode?'••••':money(value);
  const methods=[{key:'pix' as const,label:'Pix',icon:QrCode,value:data.revenueByMethod.pix||0},{key:'dinheiro' as const,label:'Dinheiro',icon:Banknote,value:data.revenueByMethod.dinheiro||0},{key:'cartao' as const,label:'Cartão',icon:CreditCard,value:(data.revenueByMethod.cartao||0)+(data.revenueByMethod.cartao_credito||0)+(data.revenueByMethod.cartao_debito||0)}];
  return <div className="fixed inset-0 z-[110] overflow-y-auto bg-zinc-950"><div className="sticky top-0 z-10 space-y-4 border-b border-zinc-800 bg-zinc-950/95 p-4 backdrop-blur-xl"><Header title="Extrato do dia" subtitle="Valores dos pedidos registrados" icon={Wallet} onClose={props.closeRevenue} tone="green"/><DateBar data={data} tone="green"/></div><main className="space-y-5 p-4 pb-32">
    <section className="relative overflow-hidden rounded-[28px] border border-emerald-500/20 bg-gradient-to-br from-emerald-500/[.12] to-zinc-900 p-5"><button onClick={props.togglePrivacyMode} className="absolute right-4 top-4 text-emerald-400">{props.isPrivacyMode?<EyeOff size={19}/>:<Eye size={19}/>}</button><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-400">Valor bruto registrado</p><p className="mt-2 font-heading text-3xl font-black text-emerald-300">{hidden(data.faturamentoTotal)}</p><div className="mt-5 grid grid-cols-3 gap-2"><Small value={hidden(data.receivedTotal)} label="Recebido"/><Small value={hidden(data.pendingTotal)} label="Pendente"/><Small value={hidden(data.ticketMedio)} label="Ticket médio"/></div></section>
    <div className="grid grid-cols-3 gap-2">{methods.map(({key,label,icon:Icon,value})=><button key={key} onClick={()=>setFilter(current=>current===key?'all':key)} className={`rounded-2xl border p-3 text-center ${filter===key?'border-emerald-500 bg-emerald-500/10':'border-zinc-800 bg-zinc-900/50'}`}><Icon size={18} className="mx-auto text-zinc-400"/><p className="mt-2 text-[10px] font-bold text-zinc-500">{label}</p><p className="mt-1 truncate text-xs font-black">{hidden(value)}</p></button>)}</div>
    <section><div className="mb-3 flex items-center justify-between"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-zinc-400"><Receipt size={15}/>Lançamentos</p><span className="text-xs text-zinc-600">{rows.length}</span></div><div className="space-y-2">{rows.map(item=><button key={item.id} onClick={()=>router.push(`/entregas/details?id=${item.id}`)} className="flex w-full items-center gap-3 rounded-2xl border border-zinc-800 bg-zinc-900/45 p-3 text-left"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.origin==='loja'?'bg-emerald-500/10 text-emerald-400':'bg-red-500/10 text-red-400'}`}>{item.origin==='loja'?<Store size={18}/>:<Package size={18}/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.customer_name||`Pedido #${item.order_id||'sem número'}`}</p><p className="mt-1 truncate text-[11px] text-zinc-500"><Clock3 size={10} className="mr-1 inline"/>{time(deliveryDate(item))} • {payment(item)}</p>{item.address_string&&<p className="mt-1 truncate text-[10px] text-zinc-600"><MapPin size={9} className="mr-1 inline"/>{item.address_string}</p>}</div><div className="text-right"><p className="text-sm font-black text-emerald-400">{hidden(item.value||0)}</p>{item.completed?<CheckCircle2 size={14} className="ml-auto mt-1 text-emerald-500"/>:<Clock3 size={14} className="ml-auto mt-1 text-amber-400"/>}</div></button>)}{!rows.length&&<Empty icon={Receipt} text="Nenhum lançamento neste filtro."/>}</div></section>
  </main></div>;
}

function Stat({value,label,tone}:{value:number;label:string;tone?:'green'}){return <div className={`rounded-2xl border p-3 ${tone==='green'?'border-emerald-500/20 bg-emerald-500/[.06]':'border-zinc-800 bg-zinc-900/50'}`}><p className="text-xl font-black">{value}</p><p className="text-[10px] text-zinc-500">{label}</p></div>;}
function Small({value,label}:{value:string;label:string}){return <div><p className="truncate text-xs font-black">{value}</p><p className="mt-1 text-[9px] uppercase text-zinc-500">{label}</p></div>;}
function Empty({icon:Icon,text}:{icon:typeof Receipt;text:string}){return <div className="rounded-3xl border border-dashed border-zinc-800 py-14 text-center"><Icon className="mx-auto text-zinc-700"/><p className="mt-3 text-sm text-zinc-500">{text}</p></div>;}
