// app/abastecimentos/page.tsx
'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, PackageOpen, Plus, Search, UserRound, Wallet } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { buildStockSupplyMetrics, money, SUPPLY_STATUS_LABELS, supplyDate, supplyTotal } from '@/lib/stock-supply';
import type { StockSupplyStatus } from '@/types';

const monthKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
export default function StockSuppliesPage() {
  const router = useRouter(); const supplies = useAppStore((state) => state.stockSupplies);
  const [month, setMonth] = useState(() => new Date()); const [query, setQuery] = useState(''); const [status, setStatus] = useState<StockSupplyStatus | 'todos'>('todos');
  const monthly = useMemo(() => supplies.filter((item) => monthKey(supplyDate(item)) === monthKey(month)), [month, supplies]);
  const filtered = useMemo(() => monthly.filter((item) => { const haystack = `${item.supplier || ''} ${item.purchaser_name || ''} ${item.items.map((x) => x.name).join(' ')}`.toLocaleLowerCase('pt-BR'); return (status === 'todos' || item.status === status) && haystack.includes(query.trim().toLocaleLowerCase('pt-BR')); }), [monthly, query, status]);
  const metrics = useMemo(() => buildStockSupplyMetrics(monthly), [monthly]);
  const moveMonth = (amount: number) => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + amount, 1));
  return <div className="flex flex-col gap-5 pb-28">
    <header className="flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={() => router.replace('/loja')} className="flex h-12 w-12 items-center justify-center rounded-full border border-zinc-800 bg-zinc-900 text-zinc-400"><ChevronLeft size={21}/></button><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-400">Estoque operacional</p><h1 className="font-heading text-2xl font-black text-zinc-100">Abastecimentos</h1></div></div><button onClick={() => router.push('/abastecimentos/novo')} className="flex h-12 items-center gap-2 rounded-2xl bg-amber-500 px-4 font-black text-zinc-950"><Plus size={18}/>Novo</button></header>
    <section className="flex items-center justify-between rounded-[26px] border border-zinc-800 bg-zinc-900/50 p-3"><button onClick={() => moveMonth(-1)} className="flex h-12 w-12 items-center justify-center rounded-2xl bg-zinc-800 text-zinc-400"><ChevronLeft size={18}/></button><div className="text-center"><CalendarDays size={16} className="mx-auto text-amber-400"/><p className="mt-1 font-black capitalize text-zinc-100">{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</p></div><button onClick={() => moveMonth(1)} className="flex h-12 w-12 items-center justify-center rounded-2xl bg-zinc-800 text-zinc-400"><ChevronRight size={18}/></button></section>
    <section className="grid grid-cols-2 gap-3"><Metric icon={Wallet} label="Gasto no mês" value={money(metrics.totalAmount)}/><Metric icon={PackageOpen} label="Itens registrados" value={String(metrics.itemCount)}/><Metric icon={UserRound} label="Abastecimentos" value={String(metrics.count)}/><Metric icon={CheckCircle2} label="Aguardando ação" value={String(metrics.pendingCount + metrics.uncheckedCount)}/></section>
    <div className="relative"><Search size={19} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar produto, fornecedor ou comprador" className="h-14 w-full rounded-2xl border border-zinc-800 bg-zinc-900/50 pl-12 pr-4 text-sm text-zinc-100 outline-none focus:border-amber-500"/></div>
    <div className="flex gap-2 overflow-x-auto pb-1">{(['todos','solicitado','em_compra','recebido','conferido'] as const).map((key)=><button key={key} onClick={()=>setStatus(key)} className={`shrink-0 rounded-xl border px-4 py-2 text-xs font-bold ${status===key?'border-amber-500/40 bg-amber-500/10 text-amber-400':'border-zinc-800 bg-zinc-900 text-zinc-500'}`}>{key==='todos'?'Todos':SUPPLY_STATUS_LABELS[key]}</button>)}</div>
    <section className="space-y-3">{filtered.map((item)=><button key={item.id} onClick={()=>router.push(`/abastecimentos/detalhes?id=${item.id}`)} className="w-full rounded-[26px] border border-zinc-800 bg-zinc-900/50 p-5 text-left active:scale-[.99]"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-amber-500/10 px-2.5 py-1 text-[9px] font-black uppercase text-amber-400">{SUPPLY_STATUS_LABELS[item.status]}</span><p className="mt-3 font-heading text-lg font-black text-zinc-100">{item.supplier || 'Abastecimento de estoque'}</p><p className="mt-1 text-xs text-zinc-500">{item.items.slice(0,3).map(x=>x.name).join(' • ')}{item.items.length>3?` +${item.items.length-3}`:''}</p></div><p className="font-black text-emerald-400">{money(supplyTotal(item))}</p></div><div className="mt-4 flex items-center justify-between border-t border-zinc-800/70 pt-3 text-[10px] text-zinc-500"><span className="flex items-center gap-1"><UserRound size={12}/>{item.purchaser_name || 'Comprador não informado'}</span><span>{supplyDate(item).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</span></div></button>)}{!filtered.length&&<div className="rounded-[28px] border border-dashed border-zinc-800 py-14 text-center"><PackageOpen size={34} className="mx-auto text-zinc-700"/><p className="mt-3 text-sm font-bold text-zinc-400">Nenhum abastecimento encontrado</p><p className="mt-1 text-xs text-zinc-600">Registre os itens trazidos para o estoque.</p></div>}</section>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Wallet}){return <div className="rounded-[22px] border border-zinc-800 bg-zinc-900/45 p-4"><Icon size={15} className="text-amber-400"/><p className="mt-3 truncate font-heading text-lg font-black text-zinc-100">{value}</p><p className="mt-1 text-[10px] font-bold text-zinc-600">{label}</p></div>}
