// app/motoboys/details/page.tsx
'use client';
import { Suspense } from 'react';import { useRouter,useSearchParams } from 'next/navigation';import { Bike,Calculator,CheckCircle2,ChevronLeft,ChevronRight,Edit3,PackageOpen,UserRound } from 'lucide-react';import { useAppStore } from '@/store/useAppStore';import { calculateMotoboyFee,getMotoboyRoutes,routeOperationalDate } from '@/lib/motoboy-analytics';import { MotoboyOperationalMemory } from '@/components/intelligence/EntityOperationalMemory';
function Content(){const router=useRouter();const id=useSearchParams().get('id');const motoboy=useAppStore(state=>state.motoboys.find(item=>item.id===id));const routes=useAppStore(state=>state.routes);const deliveries=useAppStore(state=>state.deliveries);if(!motoboy)return <div className="py-20 text-center"><p className="font-bold">Entregador não encontrado</p><button onClick={()=>router.push('/motoboys')} className="mt-4 text-sm font-bold text-sky-400">Voltar</button></div>;const linkedRoutes=getMotoboyRoutes(motoboy,routes).sort((a,b)=>new Date(routeOperationalDate(b)||0).getTime()-new Date(routeOperationalDate(a)||0).getTime());const routeIds=new Set(linkedRoutes.map(route=>route.id));const linkedDeliveries=deliveries.filter(delivery=>routeIds.has(delivery.route_id));const completed=linkedDeliveries.filter(delivery=>delivery.completed);const feeExample=calculateMotoboyFee(motoboy.payment_rule,completed.length);return <div className="flex flex-col gap-5 pb-28"><header className="flex items-center gap-3"><button onClick={()=>router.push('/motoboys')} className="flex h-10 w-10 items-center justify-center rounded-full bg-zinc-900 text-zinc-400"><ChevronLeft size={21}/></button><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-sky-400">Ficha do entregador</p><h1 className="truncate font-heading text-xl font-bold">{motoboy.name}</h1></div><button onClick={()=>router.push(`/motoboys/editar?id=${motoboy.id}`)} className="flex h-10 items-center gap-2 rounded-xl bg-amber-500 px-3 text-xs font-black text-zinc-950"><Edit3 size={15}/>Editar</button></header>
  <section className="rounded-[26px] border border-zinc-800 bg-zinc-900/45 p-5"><div className="flex items-center gap-3"><div className={`flex h-14 w-14 items-center justify-center rounded-2xl ${motoboy.active?'bg-sky-500/10 text-sky-400':'bg-zinc-800 text-zinc-600'}`}><UserRound size={25}/></div><div><p className="text-lg font-black text-zinc-100">{motoboy.active?'Ativo':'Inativo'}</p><p className="text-xs font-bold uppercase text-zinc-500">{motoboy.type||'fixo'}</p></div></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-zinc-800 pt-4 text-center"><Stat value={String(linkedRoutes.length)} label="Rotas"/><Stat value={String(completed.length)} label="Entregas"/><Stat value={String(linkedRoutes.filter(route=>route.status==='fechada').length)} label="Finalizadas"/></div></section>
  <button onClick={()=>router.push(`/motoboys/acerto?id=${motoboy.id}`)} className="flex h-14 items-center justify-center gap-2 rounded-2xl bg-emerald-500 font-black text-zinc-950"><Calculator size={19}/>Abrir acerto de caixa</button>
  <section className={`rounded-[22px] border p-4 ${motoboy.payment_rule?'border-sky-500/20 bg-sky-500/5':'border-amber-500/20 bg-amber-500/5'}`}><p className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Regra atual</p><p className="mt-2 text-sm font-bold text-zinc-200">{motoboy.payment_rule?feeExample.description:'Pagamento ainda não configurado'}</p>{motoboy.payment_rule&&<p className="mt-1 text-[10px] text-zinc-500">A simulação acima considera todo o histórico concluído apenas para explicar a fórmula; o acerto calcula por dia.</p>}</section>
  <MotoboyOperationalMemory motoboyId={motoboy.id}/>
  <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-heading text-lg font-bold">Histórico de rotas</h2><p className="text-xs text-zinc-500">Rotas ligadas por ID e legado por nome</p></div><Bike size={19} className="text-sky-400"/></div><div className="flex flex-col gap-2">{linkedRoutes.map(route=>{const routeDeliveries=linkedDeliveries.filter(delivery=>delivery.route_id===route.id);return <button key={route.id} onClick={()=>router.push(`/rotas/details?id=${route.id}`)} className="rounded-[20px] border border-zinc-800 bg-zinc-900/45 p-4 text-left"><div className="flex items-center justify-between"><div><p className="font-bold text-zinc-200">{route.name}</p><p className="mt-1 text-xs text-zinc-500">{routeOperationalDate(route)?new Date(routeOperationalDate(route)!).toLocaleString('pt-BR'):'Data não registrada'}</p></div><div className="text-right"><p className="flex items-center justify-end gap-1 text-xs font-bold text-zinc-300"><PackageOpen size={13}/>{routeDeliveries.filter(item=>item.completed).length}/{routeDeliveries.length}</p><span className={`mt-1 inline-block rounded-md px-2 py-0.5 text-[9px] font-bold ${route.status==='fechada'?'bg-emerald-500/10 text-emerald-400':'bg-sky-500/10 text-sky-400'}`}>{route.status==='fechada'?'Finalizada':'Aberta'}</span><ChevronRight size={15} className="ml-auto mt-1 text-zinc-600"/></div></div></button>})}{!linkedRoutes.length&&<div className="rounded-3xl border border-dashed border-zinc-800 py-12 text-center"><CheckCircle2 className="mx-auto text-zinc-700"/><p className="mt-3 text-sm text-zinc-500">Nenhuma rota vinculada.</p></div>}</div></section>
 </div>;}
function Stat({value,label}:{value:string;label:string}){return <div><p className="text-sm font-black">{value}</p><p className="text-[10px] text-zinc-500">{label}</p></div>;}
export default function MotoboyDetailsPage(){return <Suspense fallback={<p className="py-20 text-center text-zinc-500">Carregando...</p>}><Content/></Suspense>;}
